#!/usr/bin/env python3
"""
Offline GPT-4o analysis of FN and FP cases.

Reads fp_cases.json and fn_cases.json (generated by running the CV analysis),
sends each account to GPT-4o, and writes a structured report to llm_review_report.txt.

Usage:
    python3 llm_review.py [--fp-only | --fn-only] [--lang en|fr]
"""

import argparse
import json
import os
import re
import time
import sys

_VERDICT_RE = re.compile(r"\[\[\[([^\]]+)\]\]\]")

SYSTEM_PROMPT = """You are an expert bot detection analyst reviewing social media accounts.
For each account, identify specific signals that indicate it's a bot or a genuine human.
Focus on patterns that could generalize to detecting similar accounts.

End your analysis with your verdict in this exact format:
[[[YES|confidence|brief_reason]]]  ← if bot
[[[NO|confidence|brief_reason]]]   ← if human

confidence is 0.0-1.0, brief_reason under 20 words."""


def build_prompt(case: dict) -> str:
    u = case["user"]
    case_type = case["type"]
    lang = case["lang"].upper()
    dataset = case["dataset"]
    rf_score = case["bot_score"]

    header = (
        f"Account analysis request [{lang} dataset {dataset}]\n"
        f"Ground truth: {'BOT (we MISSED it)' if case_type == 'FN' else 'HUMAN (we WRONGLY flagged it)'}\n"
        f"Our model score: {rf_score:.3f}\n\n"
    )
    profile = (
        f"PROFILE:\n"
        f"  Username: {u.get('username', '?')}\n"
        f"  Display name: {u.get('name', '?')}\n"
        f"  Description: {u.get('description') or '(empty)'}\n"
        f"  Location: {u.get('location') or '(empty)'}\n"
        f"  Tweet count: {u.get('tweet_count', '?')}  Z-score: {u.get('z_score', '?')}\n\n"
    )
    posts = case.get("posts", [])
    # Show all posts (capped at 50)
    post_lines = [f"  [{p['created_at']}] {p['text']}" for p in posts[:50]]
    if len(posts) > 50:
        post_lines.append(f"  ... ({len(posts) - 50} more posts truncated)")

    return header + profile + "POSTS:\n" + "\n".join(post_lines)


def parse_verdict(text: str):
    match = _VERDICT_RE.search(text)
    if not match:
        return None
    parts = match.group(1).split("|")
    if len(parts) < 2:
        return None
    verdict = parts[0].strip().upper()
    if verdict not in ("YES", "NO"):
        return None
    try:
        confidence = float(parts[1].strip())
    except ValueError:
        return None
    reason = parts[2].strip() if len(parts) > 2 else ""
    return verdict, confidence, reason


def analyze_cases(cases: list, client, model: str = "gpt-4o", max_retries: int = 3) -> list:
    results = []
    for i, case in enumerate(cases):
        uid = case["user"]["id"]
        username = case["user"].get("username", "?")
        case_type = case["type"]
        print(f"  [{i+1}/{len(cases)}] {case_type} @{username} (score={case['bot_score']:.3f})", end="", flush=True)

        prompt = build_prompt(case)
        verdict_result = None

        for attempt in range(max_retries):
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.1,
                    max_tokens=600,
                )
                text = response.choices[0].message.content or ""
                verdict_result = parse_verdict(text)
                if verdict_result is not None:
                    break
                print(f" (retry {attempt+1})", end="", flush=True)
                time.sleep(1.0)
            except Exception as e:
                print(f" (error: {e})", end="", flush=True)
                if attempt < max_retries - 1:
                    time.sleep(2.0)

        if verdict_result:
            verdict, confidence, reason = verdict_result
            agreement = (
                "✓ AGREES" if (case_type == "FN" and verdict == "YES") or (case_type == "FP" and verdict == "NO")
                else "✗ DISAGREES"
            )
            print(f" → {verdict} ({confidence:.2f}) [{agreement}]")
            results.append({
                **case,
                "llm_verdict": verdict,
                "llm_confidence": confidence,
                "llm_reason": reason,
                "llm_full_response": text,
                "llm_agrees_with_ground_truth": (
                    (case_type == "FN" and verdict == "YES") or
                    (case_type == "FP" and verdict == "NO")
                ),
            })
        else:
            print(" → ABSTAIN")
            results.append({**case, "llm_verdict": "ABSTAIN", "llm_confidence": 0.0,
                            "llm_reason": "parse failed", "llm_agrees_with_ground_truth": None})

    return results


def write_report(results: list, output_path: str):
    fn_results = [r for r in results if r["type"] == "FN"]
    fp_results = [r for r in results if r["type"] == "FP"]

    lines = ["=" * 70, "GPT-4o ANALYSIS REPORT — FN and FP Cases", "=" * 70, ""]

    # Summary
    fn_caught = sum(1 for r in fn_results if r.get("llm_verdict") == "YES")
    fp_correct = sum(1 for r in fp_results if r.get("llm_verdict") == "NO")
    lines += [
        f"FN cases (missed bots): {len(fn_results)} total, GPT caught {fn_caught} ({fn_caught/max(len(fn_results),1)*100:.0f}%)",
        f"FP cases (wrongly flagged): {len(fp_results)} total, GPT agreed they're human: {fp_correct} ({fp_correct/max(len(fp_results),1)*100:.0f}%)",
        "",
    ]

    for section, cases in [("FALSE NEGATIVES — Bots we missed", fn_results),
                            ("FALSE POSITIVES — Humans we wrongly flagged", fp_results)]:
        lines += ["─" * 70, section, "─" * 70, ""]
        for r in sorted(cases, key=lambda x: x.get("llm_confidence", 0), reverse=True):
            u = r["user"]
            lines += [
                f"@{u.get('username')}  [{r['lang'].upper()} ds{r['dataset']}]  "
                f"RF={r['bot_score']:.3f}  LLM={r.get('llm_verdict','?')} ({r.get('llm_confidence',0):.2f})",
                f"  Name: {u.get('name')}  |  Desc: {(u.get('description') or '(empty)')[:80]}",
                f"  Reason: {r.get('llm_reason', 'n/a')}",
                "",
            ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\nReport written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Offline GPT-4o FN/FP analysis")
    parser.add_argument("--fp-only", action="store_true")
    parser.add_argument("--fn-only", action="store_true")
    parser.add_argument("--lang", choices=["en", "fr"], default=None)
    parser.add_argument("--model", default="gpt-4o")
    args = parser.parse_args()

    try:
        from openai import OpenAI
    except ImportError:
        print("openai package not installed. Run: pip install openai")
        sys.exit(1)

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("OPENAI_API_KEY not set.")
        sys.exit(1)

    client = OpenAI(api_key=api_key)

    cases = []
    fn_file = "fn_cases_all.json" if os.path.exists("fn_cases_all.json") else "fn_cases.json"
    fp_file = "fp_cases_all.json" if os.path.exists("fp_cases_all.json") else "fp_cases.json"

    if not args.fp_only:
        with open(fn_file) as f:
            cases += json.load(f)
        print(f"Loaded FN cases from {fn_file}")
    if not args.fn_only:
        with open(fp_file) as f:
            cases += json.load(f)
        print(f"Loaded FP cases from {fp_file}")

    if args.lang:
        cases = [c for c in cases if c["lang"] == args.lang]

    if not cases:
        print("No cases to analyze.")
        sys.exit(0)

    print(f"Analyzing {len(cases)} cases with {args.model}...")
    results = analyze_cases(cases, client, model=args.model)
    write_report(results, "llm_review_report.txt")


if __name__ == "__main__":
    main()
