"""
Username similarity clustering and chain-ban post-processing.

Two bots generated by the same script often share a username pattern:
  JeanDupont30, JeanDupont31
  claude123, claude456
  workoutwarrior_1, workoutwarrior_2

We build clusters of similar usernames, add cluster size as a feature,
then apply a "chain ban" boost: if one cluster member is flagged, the
whole cluster gets a score lift.
"""

from __future__ import annotations

from difflib import SequenceMatcher


# ---------------------------------------------------------------------------
# Union-Find for clustering
# ---------------------------------------------------------------------------

class _UnionFind:
    def __init__(self, keys: list):
        self.parent = {k: k for k in keys}

    def find(self, x):
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a, b):
        self.parent[self.find(a)] = self.find(b)

    def clusters(self):
        groups: dict[str, list] = {}
        for k in self.parent:
            root = self.find(k)
            groups.setdefault(root, []).append(k)
        return list(groups.values())


# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def _username_sim(a: str, b: str) -> float:
    """Character-level similarity ratio between two usernames (case-insensitive)."""
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def build_clusters(users: list, sim_threshold: float = 0.75) -> dict:
    """
    Return {user_id: cluster_size} for all users.
    Accounts with username similarity >= sim_threshold are in the same cluster.
    Accounts that don't match anyone have cluster_size = 1.
    """
    if not users:
        return {}

    usernames = {u["id"]: (u.get("username") or "") for u in users}
    ids = [u["id"] for u in users]
    uf = _UnionFind(ids)

    # O(n²) — fine for dataset sizes of 100-500 users
    for i in range(len(ids)):
        for j in range(i + 1, len(ids)):
            if _username_sim(usernames[ids[i]], usernames[ids[j]]) >= sim_threshold:
                uf.union(ids[i], ids[j])

    cluster_sizes = {}
    for cluster in uf.clusters():
        size = len(cluster)
        for uid in cluster:
            cluster_sizes[uid] = size

    return cluster_sizes


def chain_ban_boost(
    scores: dict,
    users: list,
    threshold: float,
    boost: float = 0.15,
    sim_threshold: float = 0.75,
) -> dict:
    """
    Post-processing: if any account in a username cluster is flagged as a bot
    (score >= threshold), boost all other cluster members by `boost`.

    Only applied to clusters of size >= 2.
    Returns updated scores dict (does not mutate input).
    """
    cluster_sizes = build_clusters(users, sim_threshold)
    usernames = {u["id"]: (u.get("username") or "") for u in users}
    ids = [u["id"] for u in users]

    # Find which clusters contain at least one flagged bot
    # We need to re-derive cluster membership
    uf = _UnionFind(ids)
    for i in range(len(ids)):
        for j in range(i + 1, len(ids)):
            if _username_sim(usernames[ids[i]], usernames[ids[j]]) >= sim_threshold:
                uf.union(ids[i], ids[j])

    # Group by cluster root
    clusters: dict[str, list] = {}
    for uid in ids:
        root = uf.find(uid)
        clusters.setdefault(root, []).append(uid)

    updated = dict(scores)
    for members in clusters.values():
        if len(members) < 2:
            continue
        # If any member is flagged, boost all others
        if any(scores.get(uid, 0) >= threshold for uid in members):
            for uid in members:
                if scores.get(uid, 0) < threshold:
                    updated[uid] = min(0.95, scores.get(uid, 0) + boost)

    return updated
